config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'omniauth_callbacks'
  }
  resources :dashboard
  get '/hosting-dashboard', to: 'dashboard#dashboard'
  root 'static_pages#home'
  resources :users
  resources :listings do
    resources :images, only: [:create, :destroy]
    resources :bookings
    member do
      get 'room'
      get 'description'
      get 'price'
      get 'photos'
      get 'amenity'
      get 'location'
      get 'check_current_bookings'
      get 'review_booking'
    end
  end

  get 'search' => 'search#search'
  get '/bookings', to: 'bookings#bookings', as: 'bookings'
  resources :reviews, only: [:create]

  get '/contact_us', to: "static_pages#contact_us"
  get '/about_us', to: "static_pages#about_us"
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_many :images
  has_many :bookings, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!
  before_action :fetch_listing, except: [:new, :create, :index]
  include ReviewsHelper

  def index
    @listing = Listing.new
    @listing_list = Listing.where(user_id: current_user.id).paginate(page: params[:page], per_page: 4)
  end

  def show
    @host_details = User.find(@listing.user_id)
    @carousel = @listing.images
    @listing_reviews = fetch_reviews(@listing)
    @review_average = fetch_review_score(@listing)
  end

  def create
    @listing = Listing.new(listing_params)
    if @listing.save
      flash[:notice] = 'Listing added successfully'
      redirect_to room_listing_url(@listing)
    else
      flash[:alert] = 'Failed to add Listing'
      redirect_to listings_url
    end
  end

  def room
  end

  def price
  end

  def description
  end

  def photos
    @images = @listing.images

  end

  def amenity
  end

  def location
  end

  def update
    @final_data = is_ready_to_publish(@listing) ? listing_params.merge(is_active: true) : listing_params.merge(is_active: false)
    if @listing.update_attributes(@final_data)
      flash[:notice] = 'Updated Listing Details!'
    else
      flash[:alert] = 'Update Failed!'
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    Listing.find(params[:id]).destroy
    flash[:alert] = 'Listing Deleted!'
    redirect_to listings_url
  end

  def check_current_bookings
    today = Date.today
    booking = @listing.bookings.where("check_in_date >= ? OR check_out_date >= ?", today, today)

    render json: booking
  end

  def review_booking
    check_in_date = Date.parse(params[:check_in_date])
    check_out_date = Date.parse(params[:check_out_date])

    result = { conflict: check_conflicts(check_in_date, check_out_date, @listing) }

    render json: result
  end

  private
  def listing_params
    params.require(:listing).permit(
      :user_id,
      :listing_name,
      :home_type,
      :room_type,
      :price,
      :accomodate,
      :bedroom_count,
      :bathroom_count,
      :listing_description,
      :has_internet,
      :has_tv,
      :has_kitchen,
      :has_heating,
      :has_air_conditioning,
      :address
    )
  end

  def fetch_listing
    @listing = Listing.find(params[:id])
  end

  def check_conflicts(check_in_date, check_out_date, listing)
    check = @listing.bookings.where('? < check_in_date AND check_out_date < ?', check_in_date, check_out_date)
    check.size > 0 ? true : false
  end

end

app/helpers/listing_helper.rb
module ListingHelper
  def is_ready_to_publish(listing)
    listing.address.present? && listing.listing_description.present? && listing.listing_name.present? && listing.price.present?
  end

  def is_filled?(entry)
    if entry.present?
      content_tag :i, nil, class: 'fa fa-check text-success'
    else
      content_tag :i, nil, class: 'fa fa-times text-danger'
    end
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
  def is_ready_to_publish(listing)
    listing.address.present? && listing.listing_description.present? && listing.listing_name.present? && listing.price.present? && listing.images.present?
  end

  def is_filled?(entry)
    if entry.present?
      content_tag :i, nil, class: 'fa fa-check text-success'
    else
      content_tag :i, nil, class: 'fa fa-times text-danger'
    end
  end
end

app/views/listings/_booking.html.erb
<%= form_for [@listing, @listing.bookings.new] do |f| %>
    <div class="border rounded border-success" style="width: 550px;height: 420px;margin-top: 25px;">
        <div class="row">
            <div class="col">
                <div class="row">
                    <div class="col-xl-3">
                        <h2 class="MontserratFont" style="margin-top: 45px;margin-left: 38px;">$<%= @listing.price%></h2>
                    </div>
                    <div class="col-xl-9">
                        <p style="margin-top: 59px;">/night</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <span id="message" style="margin-left: 38px;"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row" style="margin-top: 20px;">
            
            <div class="col">
                <%= f.hidden_field :listing_id, value: @listing.id %>
                <%= f.text_field :check_in_date, id: "check_in_date", class: "form-control col-lg-10", readonly: true, placeholder: "Check In Date", style: "margin-right: 15px;margin-left: 30px;" %>
            </div>
            <div class="col">
                <%= f.text_field :check_out_date, id: "check_out_date", class: "form-control col-lg-10", readonly: true, placeholder: "Check Out Date", style: "margin-right: 30px;margin-left: 15px;" , disabled: true %>
            </div>
        </div>
        <hr style="width: 485px;" />
        <div id="preview" style="display: none;" >
            <div class="row MontserratFont">
                <div class="col">
                    <p class="text-center">PRICE</p>
                </div>
                <div class="col">
                    <p class="text-center">$<%= @listing.price %></p>
                </div>
            </div>
            <div class="row MontserratFont">
                <div class="col">
                    <p class="text-center">Night(s)</p>
                </div>
                <div class="col">
                    <p class="text-center">x <span id="nights"></span> </p>
                </div>
            </div>
            <hr style="width: 485px;" />
            <div class="row">
                <div class="col">
                    <h4 class="text-center">TOTAL</h4>
                </div>
                <div class="col">
                    <p class="text-center MontserratFont">$ <span id="total_price"></span></p>
                </div>
            </div>
            <div class="row text-center d-xl-flex justify-content-xl-center">
                <div class="col text-center d-xl-flex justify-content-xl-center">
                    <%= f.submit "RESERVE", id: 'reserve', class: "btn btn-success d-xl-flex roundedButton" %>
                </div>
            </div>
        </div>
    </div>
<% end %>

<script>
    function checkSchedule(date){
        schedule = date.getDate() + "-" + (date.getMonth()+1) + "-" + date.getFullYear();
        return [$.inArray(schedule, unavailableDates) == -1];
    }

    $(function() {
        unavailableDates = [];

        $.ajax({
            url: '<%= check_current_bookings_listing_path(@listing) %>',
            dataType: 'json',
            success: function(data){
                console.log("Success");
                $.each(data, function(arrayID, arrayValue) {
                    for(var i = new Date(arrayValue.check_in_date); i <= new Date(arrayValue.check_out_date); i.setDate(i.getDate()+1)){
                        unavailableDates.push($.datepicker.formatDate('d-m-yy', i));
                    }
                })
                console.log(unavailableDates)
                $("#check_in_date").datepicker({
                    numberOfMonths:1,
                    dateFormat: 'dd-mm-yy',
                    minDate: 0,
                    maxDate: '3m',
                    beforeShowDay: checkSchedule,
                    onSelect: function(selectedDate) {
                        $("#check_out_date").datepicker("option", "minDate", selectedDate);
                        $('#check_out_date').attr("disabled", false);

                        var check_in = $('#check_in_date').datepicker('getDate');
                        var check_out = $('#check_out_date').datepicker('getDate');
                        var nights = (check_out - check_in)/1000/3600/24;

                        var input = {
                            'check_in_date': check_in,
                            'check_out_date': check_out
                        }

                        $.ajax({
                            url: '<%= review_booking_listing_path(@listing) %>',
                            data: input,
                            success: function(data){
                                if(data.conflict){
                                    $('#message').text('Selected Dates are Unavailable');
                                    $('#preview').hide();
                                    $('#reserve').attr('disabled', true)
                                } else {
                                    $('#message').text('Selected Dates are Available');
                                    $('#preview').show();
                                    $('#reserve').attr('disabled', false)
                                    if(check_in.getTime() == check_out.getTime()){
                                        nights = 1;
                                    }
                                }
                                var total_price = nights * <%= @listing.price %>
                                $('#nights').text(nights);
                                $('#total_price').text(total_price);
                            }
                        })
                    }
                });

                $("#check_out_date").datepicker({
                    numberOfMonths:1,
                    dateFormat: 'dd-mm-yy',
                    minDate: 0,
                    maxDate: '3m',
                    beforeShowDay: checkSchedule,
                    onSelect: function(selectedDate) {
                        $("#check_in_date").datepicker("option", "maxDate", selectedDate);

                        var check_in = $('#check_in_date').datepicker('getDate');
                        var check_out = $('#check_out_date').datepicker('getDate');
                        var nights = (check_out - check_in)/1000/3600/24;

                        var input = {
                            'check_in_date': check_in,
                            'check_out_date': check_out
                        }

                        $.ajax({
                            url: '<%= review_booking_listing_path(@listing) %>',
                            data: input,
                            success: function(data){
                                if(data.conflict){
                                    $('#message').text('Selected Dates are Unavailable');
                                    $('#preview').hide();
                                    $('#reserve').attr('disabled', true)
                                } else {
                                    $('#message').text('Selected Dates are Available');
                                    $('#preview').show();
                                    $('#reserve').attr('disabled', false)
                                    if(check_in.getTime() == check_out.getTime()){
                                        nights = 1;
                                    }
                                }
                                var total_price = nights * <%= @listing.price %>
                                $('#nights').text(nights);
                                $('#total_price').text(total_price);
                            }
                        })


                    }
                });
            }
        })
    });
</script>

app/views/listings/_gallery.html.erb
<div role="tabpanel" class="tab-pane fade show active" id="tab-3">
    <div class="row" style="margin-top: 50px; margin-bottom: 230px;">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 d-flex justify-content-center">
            <% if @carousel.present? %>
                <div class="carousel slide" data-ride="carousel" id="carousel-1">
                    <div class="carousel-inner" role="listbox">
                        <% @carousel.each do |image| %>
                            <div class="carousel-item <%= image.id == @carousel.first.id ? 'active' : '' %>">
                                <%= image_tag image.image, class: "mw-100 d-block gallery h-100" %>
                            </div>
                        <% end %>                    
                    </div>
                    <div>
                        <a class="carousel-control-prev" href="#carousel-1" role="button" data-slide="prev"><span class="carousel-control-prev-icon"></span><span class="sr-only">Previous</span></a>
                        <a class="carousel-control-next" href="#carousel-1" role="button" data-slide="next"><span class="carousel-control-next-icon"></span><span class="sr-only">Next</span></a>
                    </div>
                    <ol class="carousel-indicators">
                        <% @carousel.each do |image| %>
                            <li data-target="#carousel-1" data-slide-to="<%= image.id %>" class="active"></li>
                        <% end %>
                    </ol>
                </div>
            <% else %>
            <p> No Images Found </p>
            <% end %>
        </div>
    </div>
</div>

app/views/listings/_sidebar.html.erb
<div class="col-xl-4 col-md-4">
    <ul class="list-group">
        <li class="list-group-item">
            <div class="row">
            <div class="col-xl-10 col-md-10">
                <%= link_to raw("<span>Room</span>"), room_listing_url(@listing) %>
            </div>
                <div class="col-xl-2 col-md-2"><i class="fa fa-check text-success"></i></div>
            </div>
        </li>
        <li class='list-group-item'>
            <div class='row'>
                <div class='col-xl-10 col-md-10'>
                    <%= link_to raw("<span>Price</span>"), price_listing_url(@listing) %>
                </div>
                <div class='col-xl-2 col-md-2'><%= is_filled?(@listing.price) %></div>
            </div>
        </li>
        <li class='list-group-item'>
            <div class='row'>
                <div class='col-xl-10 col-md-10'>
                    <%= link_to raw("<span>Description</span>"), description_listing_url(@listing)%>
                </div>
                <div class='col-xl-2 col-md-2'><%= is_filled?(@listing.listing_description) %></div>
            </div>
        </li>
        <li class='list-group-item'>
            <div class='row'>
                <div class='col-xl-10 col-md-10'>
                    <%= link_to raw("<span>Photos</span>"), photos_listing_url(@listing)%>
                </div>
                <div class='col-xl-2 col-md-2'><%= is_filled?(@listing.images) %></div>
            </div>
        </li>
        <li class='list-group-item'>
            <div class='row'>
                <div class='col-xl-10 col-md-10'>
                    <%= link_to raw("<span>Amenities</span>"), amenity_listing_url(@listing)%>
                    </div>
                <div class='col-xl-2 col-md-2'><i class='fa fa-check text-success'></i></div>
            </div>
        </li>
        <li class='list-group-item'>
            <div class='row'>
                <div class='col-xl-10 col-md-10'>
                    <%= link_to raw("<span>Location</span>"), location_listing_url(@listing)%>
                </div>
                <div class='col-xl-2 col-md-2'><%= is_filled?(@listing.address) %></div>
            </div>
        </li>
        <li class="list-group-item">
        <%= form_for(@listing) do |f| %>
            <%= f.hidden_field :is_active, value: true %>
            <%= f.submit "Publish", disabled: !is_ready_to_publish(@listing), class: "btn btn-block btn-success col-lg-12 col-md-12"%>
        <% end %>
        </li>
        <li class='list-group-item'>
            <%= link_to raw("<i class='fa fa-eye'></i>&nbsp;View Listing"), @listing , class: "btn btn-info col-lg-12 col-md-12"%>
        </li>
    </ul>
</div>

app/views/listings/index.html.erb
<% provide(:title, "Your Listings") %>
<div class="container-fluid">
    <%= render 'new' %>
    <div class="row">
        <%= render 'layouts/navigation' %>
        <div class="col-lg-9 col-md-9" style="margin-bottom: 100px">
            <div class="d-none d-lg-block mr-5 pr-5">
                <div class="row mt-5 pt-5">
                    <div class="col">
                        <h1>Your Listings</h1>
                    </div>
                    <div >
                        <button class="btn btn-outline-success d--flex justify-content-end roundedButton" type="button" data-toggle="modal" data-target="#newListingModal" >Add a new Listing &nbsp;<i class="fa fa-plus"></i></button>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <hr />
                    </div>
                </div>
                <div class="row" style="margin-top: 20px;">
                    <div class="col-lg-12 col-md-12">
                        <div class="row">
                            <% @listing_list.each do |item| %>
                                <div class="col-lg-3 col-md-3">
                                    <div class="card mx-3 my-3">    
                                        <% if item.images.present? %>
                                            <%= image_tag item.images.first.image, class: "card-img-top w-100"%>
                                        <% else %>
                                            <p> No image found </p>
                                        <% end %>
                                        <div class="card-body">
                                            <h5 class="text-center card-title"><%= item.listing_name %></h5>
                                            <div class="col">
                                                <div class="btn-group" role="group">
                                                    <%= link_to raw("View Details"), item, class: "btn btn-outline-primary d-flex justify-content-center" %>
                                                    <%= link_to raw("Edit Details"), room_listing_path(item), class: "btn btn-outline-info d-flex justify-content-center" %>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <% end %>
                        </div>
                    </div>
                </div>
                <div class="row" style="margin-top: 21px;">
                    <div class="col">
                        <nav class="d-flex justify-content-center">
                            <%= will_paginate @listing_list %>
                        </nav>
                    </div>
                </div>
            </div>
            
            <div class="d-lg-none">
                <div class="col-md-12 col-sm-12 col-xs-12 ml-4 mt-5">
                    <div class="row offset-md-3 offset-sm-3 offset-xs-3 ">
                        <div class="col-md-10 col-sm-10 col-xs-10">
                            <h1>Your Listings</h1>
                        </div>
                        <div class="col-md-1 col-sm-1 col-xs-1">
                            <button class="btn btn-outline-success roundedButton d-flex justify-content-end" type="button" data-toggle="modal" data-target="#newListingModal"><i class="fa fa-plus"></i></button>
                        </div>
                    </div>
                    <div class="row mt-4">
                        <div class="offset-md-3 offset-sm-3 offset-xs-3 col-md-9 col-sm-9 col-xs-9">
                            <% @listing_list.each do |item| %>                                
                                <div class="row">
                                    <div class="card w-100" style="margin-bottom: 20px;">
                                        <div class="card-body">
                                            <div class="row">
                                                <% if item.images.present? %>
                                                    <div class="col-md-6 col-sm-6 col-xs-6" style="background-image: url(<%= url_for(item.images.first.image) %>);
                                                        height: 150px;
                                                        width: 150px;
                                                        background-size: cover;
                                                        background-position: center;">
                                                    </div>
                                                <% else %>
                                                    <p class="m-auto"> No image found </p>
                                                <% end %>                                                
                                                <div class="col-md-6 col-sm-6 col-xs-6 py-5">
                                                    <h6><%= link_to item.listing_name, item, class:"text-dark text-break" %></h6>
                                                    <div class="btn-group mt-3 d-flex justify-content-end" role="group">
                                                        <%= link_to raw("<i class='fa fa-eye'></i>"), item, class: "btn btn-outline-primary d-flex justify-content-center" %>
                                                        <%= link_to raw("<i class='fa fa-pen'></i>"), room_listing_path(item), class: "btn btn-outline-info d-flex justify-content-center" %>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <% end %>
                            <div class="row" style="margin-top: 21px; margin-bottom: 100px;">
                                <div class="col">
                                    <nav class="d-flex justify-content-center">
                                        <%= will_paginate @listing_list %>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                <div>
            </div> 
            
        </div>
    </div>
</div>

app/views/listings/photos.html.erb
<% provide(:title, "Listing Photos") %>
<div class="container" style="margin-top: 100px;">
    <div class="row">
        <%= render'sidebar' %>
        <div class="col-xl-8 col-md-8">
            <div class="card">
                <div class="card-header">
                    <h5 class="mb-0">Photos</h5>
                </div>
                <div class="card-body">
                <%= form_for @listing, url: listing_images_path(@listing), method: "post", html: { :multipart => true }, enctype: 'multipart/form-data' do |f| %>
                    <div class="row" style="margin-bottom: 20px;">
                        <div class="col">
                            <%= file_field_tag "images[]", type: :file, multiple: true, required: true, accept: "image/jpeg,image/gif,image/png" %>
                        </div>
                    </div>
                    <div class="row" style="margin-bottom: 20px;">

                    <% @images.each do |image| %>
                        <div class="col col-lg-4" style="padding-top: 30px; padding-bottomo: 30px;">
                            <div class="card mt-4">
                                <div class="card-img-top-preview"> 
                                    <%= image_tag image.image, class: "img mw-100" %>
                                </div>
                                <div class="card-text">
                                    <%= link_to raw("<i class=' fa fa-trash text-danger'></i>&nbsp;Delete image"), listing_image_path(@listing, image), method: :delete, class: "float-right mr-3 my-3 text-danger MontserratFont" %>
                                </div>
                            </div>                            
                        </div>
                    <% end %>
                    </div>
                    <div class="row">
                        <div class="col">
                            <%= f.submit "Save", class: "btn btn-primary col-lg-12 roundedButton" %>
                        </div>
                    </div>
                <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/listings/show.html.erb
<% provide(:title, "#{@listing.listing_name}" ) %>
<script type='text/javascript' src='https://maps.googleapis.com/maps/api/js?key=AIzaSyDNeXbH-bDElDPrrO3cPtyfO4L07k4L6aY&callback=initMap'></script>
<script type='text/javascript'>
    document.addEventListener("DOMContentLoaded", function(){
        var location = {lat: Number("<%= @listing.latitude %>"), lng: Number("<%= @listing.longitude %>")};
        var map = new google.maps.Map(document.getElementById('map'),{
            center: location,
            zoom: 20
        });
        
        var marker = new google.maps.Marker({
            position: location,
            map: map
        });

        var infoWindow = new google.maps.InfoWindow({
            content: '<div id="content"><% if @listing.images.present? %><%= image_tag @listing.images.first.image, size: "400x200" %><%else%><p>No Image Found</p> <%end%></div>'
        });

        infoWindow.open(map, marker);
    });
</script>
<% if @listing.images.present? %>
    <div style='background-image: url(<%= url_for(@listing.images.first.image) %>);
        height: 600px;
        background-attachment: fixed;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;'> 
    </div>
<% else %>
    <div> 
        <h1 class="text-danger d-flex justify-content-center" style="margin-top: 250px;margin-bottom: 150px;"> No Image uploaded! </h1>
    </div>
<% end %>
<div class="container">
    <div class="row" style="margin-top: 55px;">
        <div class="col-xl-8 col-lg-8 col-md-8 col-sm-8 col-xs-8">
            <p><span style="font-size: 42px;color: #16f063;"><%= @listing.listing_name %></span> <br/> Hosted by <%= @host_details.name %></p>
        </div>
        <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-xs-4">
            <div class="row" style="margin-top: 22px;">
                <div class="col">
                    <% if @listing.user_id == current_user.id %>
                            <div class="d-none d-lg-block">
                                <%= link_to raw("<i class='fa fa-pen'></i> Edit"), room_listing_path(@listing), class: "btn btn-outline-info roundedButton", style: "margin-right: 15px; margin-left: 50px"  %>
                                <%= link_to raw("<i class='fa fa-trash'></i> Delete"), listing_url(@listing), class: "btn btn-outline-danger roundedButton", method: :delete, data: { confirm: "You sure?" },  style:"margin-left: 15px " %>
                            </div>
                            <div class="d-lg-none">
                                <div class="d-flex justify-content-end">
                                    <%= link_to raw("<i class='fa fa-pen'></i>"), room_listing_path(@listing), class: "btn btn-outline-info roundedButton" %>
                                    <%= link_to raw("<i class='fa fa-trash'></i>"), listing_url(@listing), class: "btn btn-outline-danger roundedButton", method: :delete, data: { confirm: "You sure?" } %>
                                </div>
                            </div>
                    <%end%>
                    <div class="d-none d-lg-block">
                        <h4 style="margin-bottom: 15px;"><%= pluralize(@listing_reviews.count, "Review", ) %>: <span id="general-stars" data-score="<%= @review_average %>"></span> </h4>
                    </div>
                    <div class="d-lg-none">
                        <p class="text-right mt-2" style="margin-bottom: 15px;"><%= pluralize(@listing_reviews.count, "Review", ) %>: <br/> <span id="general-stars-mobile" data-score="<%= @review_average %>"></span> </p>
                    </div>
                    <script>
                        $('#general-stars').raty({
                            readOnly: true,
                            score: function() {
                                return $(this).attr('data-score');
                            },
                            path: '/assets/'
                        });
                    </script>
                    <script>
                        $('#general-stars-mobile').raty({
                            readOnly: true,
                            score: function() {
                                return $(this).attr('data-score');
                            },
                            path: '/assets/'
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div>
                <hr />
                <ul class="nav nav-pills d-flex justify-content-center">
                    <li class="nav-item pill-1"><a role="tab" data-toggle="pill" class="nav-link active" href="#tab-1">Details</a></li>
                    <li class="nav-item pill-1"><a role="tab" data-toggle="pill" class="nav-link " href="#tab-2">Host Information</a></li>
                    <li class="nav-item pill-1"><a role="tab" data-toggle="pill" class="nav-link " href="#tab-3">Gallery</a></li>
                    <li class="nav-item pill-1"><a role="tab" data-toggle="pill" class="nav-link " href="#tab-4">Reviews</a></li>
                </ul>
                <div class="tab-content">
                    <%= render 'details' %>
                    <div role="tabpanel" class="tab-pane fade" id="tab-2">
                        <%= render 'host_information' %>
                    </div>
                    <div role="tabpanel" class="tab-pane fade" id="tab-3">
                        <%= render 'gallery'%>
                    </div>
                    <div role="tabpanel" class="tab-pane fade" id="tab-4">
                        <%= render 'reviews'%>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>