config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'omniauth_callbacks'
  }
  resources :dashboard
  get '/hosting-dashboard', to: 'dashboard#dashboard'
  root 'static_pages#home'
  resources :users
  resources :listings do
    resources :images, only: [:create, :destroy]
    resources :bookings
    member do
      get 'room'
      get 'description'
      get 'price'
      get 'photos'
      get 'amenity'
      get 'location'
      get 'check_current_bookings'
      get 'review_booking'
    end
  end

  get 'search' => 'search#search'
  get '/bookings', to: 'bookings#bookings', as: 'bookings'
  resources :reviews, only: [:create]

  get '/contact_us', to: "static_pages#contact_us"
  get '/about_us', to: "static_pages#about_us"
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  include SearchHelper
  include ReviewsHelper
  def search
    session[:address] = params[:search] if params.has_key?(:search)
    if check_if_filled?(session[:address])
      @search = Listing.where(is_active: true).near(session[:address], 5, order: 'distance')
    else
      @search = Listing.where(is_active: true)
    end

    if check_if_filled?(params[:check_in_date]) && check_if_filled?(params[:check_out_date])
      @bookings = Booking.where("'#{params[:check_in_date]}' < check_in_date  AND check_out_date < '#{params[:check_out_date]}'")
                        .pluck(:listing_id)
      @search = @search.where.not(id: @bookings)
    end
    unless @search.nil?
      @search = @search.ransack(params[:q])
      @listing_list = @search.result(distinct: true).paginate(page: params[:page], per_page: 2)
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
  def check_if_filled?(item)
    item.present? && item.empty? == false
  end
end

app/views/search/search.html.erb
<% provide(:title, "Search Results" ) %>
<script type='text/javascript' src='https://maps.googleapis.com/maps/api/js?key=AIzaSyDNeXbH-bDElDPrrO3cPtyfO4L07k4L6aY&callback=loadLocations'></script>
<script type='text/javascript'>
    function loadLocations() {
        var location = [];
        <% @listing_list.each do |pin| %>
            location.push({lat: Number("<%= pin.latitude %>"), lng: Number("<%= pin.longitude %>")});
        <% end %>
        
        var infoWindow = [];
        <% @listing_list.each do |info| %>
            infoWindow.push(new google.maps.InfoWindow({
                content: '<div id="content"><%= info.price %></div>'
            }));
        <% end %>

        var map = new google.maps.Map(document.getElementById('map'),{
            center: location[0],
            zoom: 14
        });

        var marker = [];
        for(var i=0; i<location.length; i++){
            marker[i] = new google.maps.Marker({
                position: location[i],
                map: map
            });
        }
        for(var i=0; i<location.length; i++){
            infoWindow[i].open(map, marker[i]);
        }
    }
    google.maps.event.addDomListener(window,'load', loadLocations);
</script>

<div class="container MontserratFont" style="margin-bottom: 100px;">
    <div class="row" style="margin-top: 100px;">
        <div class="col">
            <div class="row">
                <div class="col-lg-10 col-md-10 col-xs-10">
                    <h1>Find your stay today!</h1>
                </div>
                <div class="col-lg-2 col-md-2 col-xs-2 pull-right">
                    <% if @listing_list.nil? == false && @listing_list.empty? == false%>
                        <a class="btn btn-primary" data-toggle="collapse" aria-expanded="false" aria-controls="collapse-1" href="#collapse-1" role="button">Show Filters</a>
                    <% end %>
                </div>
            </div>
            <hr />            
            <%= render 'form' %>
        </div>
    </div>

    <div class="row" style="margin-top: 25px;">
        <div class="col">
            <% if @listing_list.present? == false %>
                <p>
                    <strong><em>No Listings Found!</em></strong>
                    <hr/> Please try again by selecting any of the options beside,<br /> we might be able to find something..
                </p>
            <% else %>
                <% @listing_list.each do |item| %>
                    <div class="d-none d-lg-block">
                        <div class="card" style="margin-bottom: 20px;">
                            <div class="card-body">
                                <div class="row ">
                                    <div class="col-xl-3">
                                        <div style="background-image: url(<%= url_for(item.images.first.image) %>);
                                                    height: 120px;
                                                    width: 170px;
                                                    background-size: cover;
                                                    background-position: center;"
                                        >
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="row">
                                            <div class="col">
                                                <h6><%= link_to item.listing_name, item, class:"text-dark" %></h6>
                                                <hr style="background-color: #16f063;" />
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                <ul>
                                                    <li><%= item.address %></li>
                                                    <li>$&nbsp;<%= item.price %></li>
                                                </ul>
                                            </div>
                                            <div class="col">
                                                <span class="search-listing-stars-<%= item.id %>" data-score="<%= fetch_review_score(item) %>"></span>
                                                <script>
                                                    $('.search-listing-stars-<%= item.id %>').raty({
                                                        readOnly: true,
                                                        score: function() {
                                                            return $(this).attr('data-score');
                                                        },
                                                        path: '/assets/'
                                                    });
                                                </script>
                                            </div>
                                            <div class="col-xl-1 d-xl-flex justify-content-xl-center align-items-xl-center">
                                                <%= link_to raw("<i class='fa fa-chevron-right text-info'></i>"), item %>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <% end %>
                <div class="d-lg-none">
                    <div class="row offset-sm-1">
                        <% @listing_list.each do |item| %>
                            <div class="col-sm-5 col-xs-5">
                                <div class="card my-3">
                                    <%= link_to image_tag(item.images.first.image, class: "card-img-top"), listing_path(item.id) %>
                                    <div class="card-body">
                                        <h5 class="card-title text-center"><%= link_to item.listing_name, item %></h5>
                                        <hr style="background-color: #16f063;" />
                                        <p class="card-text">
                                            <div class="col">
                                                <ul>
                                                    <li><%= item.address %></li>
                                                    <li>$&nbsp;<%= item.price %></li>
                                                </ul>
                                                <div class="d-flex justify-content-center">
                                                    <span class="search-listing-stars-mobile-<%= item.id %>" data-score="<%= fetch_review_score(item) %>"></span>
                                                    <script>
                                                        $('.search-listing-stars-mobile-<%= item.id %>').raty({
                                                            readOnly: true,
                                                            score: function() {
                                                                return $(this).attr('data-score');
                                                            },
                                                            path: '/assets/'
                                                        });
                                                    </script>
                                                </div>
                                            </div>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        <% end %>
                    </div>
                    <div class="row my-3">
                        <div class="col d-flex justify-content-center">
                            <%= will_paginate @listing_list %>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
            <% if @listing_list.nil? == false && @listing_list.empty? == false %>
                <div class="col-lg-4">
                    <div id="map" style="min-width: 200px;height: 400px;"></div>
                </div>
            <% end %>
        </div>
        <div class="row d-none d-xl-block" style="margin-top: 25px;">
            <div class="col d-flex justify-content-center">
                <%= will_paginate @listing_list %>
            </div>
        </div>
    </div>    
</div>