config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'omniauth_callbacks'
  }
  resources :dashboard
  get '/hosting-dashboard', to: 'dashboard#dashboard'
  root 'static_pages#home'
  resources :users
  resources :listings do
    resources :images, only: [:create, :destroy]
    resources :bookings
    member do
      get 'room'
      get 'description'
      get 'price'
      get 'photos'
      get 'amenity'
      get 'location'
      get 'check_current_bookings'
      get 'review_booking'
    end
  end

  get 'search' => 'search#search'
  get '/bookings', to: 'bookings#bookings', as: 'bookings'
  resources :reviews, only: [:create]

  get '/contact_us', to: "static_pages#contact_us"
  get '/about_us', to: "static_pages#about_us"
end

app/views/layouts/_footer.html.erb
<div class="d-none d-lg-block">
    <footer class="footer">
        <div class="container">
            <div class="footerContent">
                <div class="text-center">
                    <h4 class="text-white">Traveller's Nomadic Hut</h4>
                </div>
            </div>
        </div>
    </footer>
</div>

<div class="d-lg-none">
    <footer class="mobile-footer">
        <% if user_signed_in? %>
            <div class="row">
                <table class="table table-borderless mx-5">
                    <tbody>
                        <tr>
                            <td class="text-center my-2"><%= link_to raw("<h3><i class='fa fa-user-circle'></i><br/>Profile</h3"), user_path(current_user.id), class: "text-white"%></td>
                            <td class="text-center my-2"><%= link_to raw("<h3><i class='fa fa-tachometer-alt'></i><br/>Dashboard</h3"), hosting_dashboard_url, class: "text-white"%></td>
                            <td class="text-center my-2"><%= link_to raw("<h3><i class='fa fa-home'></i><br/>User Listings</h3"), listings_url, class: "text-white"%></td>
                            <td class="text-center my-2"><%= link_to raw("<h3><i class='fa fa-book'></i><br/>User Bookings</h3"), bookings_url, class: "text-white"%></td>
                            <td class="text-center my-2"><%= link_to raw("<h3><i class='fa fa-sign-out-alt'></i><br/>Logout</h3"), destroy_user_session_path, class: "text-white", method: :delete %></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        <% else %>
            <div class="row">
                <div class="col-sm-12 col-xs-12">
                    <table class="table table-borderless mx-2">
                        <tbody>
                            <tr>
                                <td class="text-center"><%= link_to raw("<h3><i class='fa fa-home'></i><br/>Home</h3>"), root_url, class: "text-white" %></td>
                                <td class="text-center"><%= link_to raw("<h3><i class='fa fa-sign-in-alt'></i><br/>Login</h3>"), new_user_session_path, class: "text-white" %></td>
                                <td class="text-center"><%= link_to raw("<h3><i class='fas fa-user'></i><br/>Sign up</h3>"), new_user_registration_url, class: "text-white" %></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        <% end %>
    </footer>
</div>

app/views/layouts/_header.html.erb
<div class="sticky-top">
    <div class="d-none d-lg-block">
    <nav class="navbar header justify-content-between">
    <div class='offset-lg-2 offset-md-2'>
        <a class="navbar-brand text-white MontserratFont"><i class="fa fa-home"></i>&nbsp;Traveller's Nomadic Hut</a>
    </div>

    <div class="pull-right col-lg-2 col-md-2 col-xs-4">
        <div class="dropdown">
        <button class="headerDropdown" data-toggle="dropdown" aria-expanded="false">
            <i class='fa fa-bars ml-2 my-2'> </i> &nbsp;
            <i class='fa fa-user-circle mr-2 my-2'> </i>
        </button>
            <div role="menu" class="dropdown-menu">
                <% if user_signed_in? %>
                    <%= link_to raw("<i class='fa fa-user-circle'></i> Profile"), user_path(current_user.id), class: "dropdown-item"%>
                    <div class="dropdown-divider"></div>
                    <%= link_to raw("<i class='fa fa-tachometer-alt'></i> Hosting Dashboard"), hosting_dashboard_url, class: "dropdown-item"%>
                    <%= link_to raw("<i class='fa fa-home'></i> Your Listings"), listings_url, class: "dropdown-item"%>
                    <%= link_to raw("<i class='fa fa-book'></i> Your Bookings"), bookings_url, class: "dropdown-item"%>
                    <div class="dropdown-divider"></div>
                    <%= link_to raw("<i class='fa fa-sign-out-alt'></i> Logout"), destroy_user_session_path, class: "dropdown-item", method: :delete %>
                <% else %>
                    <%= link_to raw("<i class='fa fa-sign-in-alt'></i> Login"), new_user_session_path, class: "dropdown-item" %>
                    <div class="dropdown-divider"></div>
                    <%= link_to raw("<i class='fas fa-user'></i> Sign up"), new_user_registration_url, class: "dropdown-item" %>  
                <% end %>
            </div>
        </div>
    </div>
    </nav>

        <nav class="navbar navigationItems justify-content-between">
            <%= link_to raw(" Home"), root_url, class: "nav-item nav-link text-dark headerItem" %>
            <%= link_to raw("Host your home"), listings_url, class: "nav-item nav-link text-dark headerItem"%>
            <%= link_to raw("About Us"), about_us_url, class: "nav-item nav-link text-dark headerItem"%>
            <%= link_to raw("Contact Us"), contact_us_url, class: "nav-item nav-link text-dark headerItem"%>
        </nav>
    </div>

    <nav class="d-lg-none navbar navbar-expand-lg navbar-dark header">
        <a class="navbar-brand text-white MontserratFont ml-5 pl-5 " href="#"><i class="fa fa-home"></i>&nbsp;Traveller's Nomadic Hut</a>
        <button class="navbar-toggler headerDropdown mr-5" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0 ml-2 pl-2">
                <%= link_to raw("<i class='fa fa-home'></i> Home"), root_url, class: "text-white dropdown-item" %>
                <%= link_to raw("<i class='fa fa-home'></i> Host your home"), listings_url, class: "text-white dropdown-item"%>
                <%= link_to raw("<i class='fa fa-user'></i> About Us"), about_us_url, class: "text-white dropdown-item"%>
                <%= link_to raw("<i class='fa fa-phone'></i> Contact Us"), contact_us_url, class: "text-white dropdown-item"%>
            </ul>
        </div>
    </nav>
</div>

app/views/layouts/_navigation.html.erb
<div class="col-xl-3 col-lg-3">
    <div class="d-none d-lg-block" style="margin-top: 50px;">
        <div class="row w-75 ml-5 pl-5">
            <div class="col navItems">
                <%= link_to raw("<h3 class='text-center linkItem'>Dashboard</h3>"), hosting_dashboard_url, class: "linkItem" %>
            </div>
        </div>
        <div class="row w-75 ml-5 pl-5">
            <div class="col navItems">
                <%= link_to raw("<h3 class='text-center linkItem'>Your Listings</h3>"), listings_url, class: "linkItem" %>
            </div>
        </div>
        <div class="row w-75 ml-5 pl-5">
            <div class="col navItems">
                <%= link_to raw("<h3 class='text-center linkItem'>Bookings</h3>"), bookings_url, class: "linkItem" %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
    <title><%= yield(:title) %> | Travellers Nomadic Hut</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/hot-sneaks/jquery-ui.css">
    </head>

    <body>
    <%= render 'layouts/header' %>
        <% flash.each do |key, value| %>
            <div class="fixed-top d-flex justify-content-center">
                <div class="alert <% if key == 'notice' %> alert-success <% else %> alert-warning <% end %> alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <%= value %>
                </div>
            </div>
        <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    </body>
</html>